--- 
  - name: Add ansible apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

  - name: Add ansible PPA from launchpad
    apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
      state: present

  - name: Update apt-cache
    apt: update_cache=yes 
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install ansible latest
    apt: 
        name: 'ansible'
        state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'